@startuml

node "Frontend" {
  component ReactJS
}

node "Backend" {
  component NodeJS
  component GraphQL
}

node "Base de Données" {
  database PostgreSQL
  database MongoDB
}

node "Middleware" {
  component ApacheKafka
}

node "Infrastructure" {
  component Docker
  component Kubernetes
  component AWS
}

ReactJS --> NodeJS : API REST/GraphQL
NodeJS --> PostgreSQL : Données Relationnelles
NodeJS --> MongoDB : Données Non-Structurées
NodeJS --> ApacheKafka : Messagerie
Docker --> Kubernetes : Orchestration
Kubernetes --> AWS : Hébergement

@enduml